source 'http://rubygems.org'

gem 'rails', '3.1.3'

gem 'sqlite3'
gem 'connection_manager', :path => File.expand_path("../../", __FILE__)

group :test do
  gem "rspec-rails", "~> 2.7"
  gem 'mocha'
  gem "autotest"
  gem 'factory_girl_rails'
  gem 'ruby-debug19'
end
